USE [master]
GO

/****** Object:  Database [MovingBox]    Script Date: 02-10-2024 13:40:28 ******/
DROP DATABASE [MovingBox]
GO

/****** Object:  Database [MovingBox]    Script Date: 02-10-2024 13:40:28 ******/
CREATE DATABASE [MovingBox]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MovingBox', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MovingBox.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MovingBox_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MovingBox_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MovingBox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MovingBox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MovingBox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MovingBox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MovingBox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MovingBox] SET ARITHABORT OFF 
GO

ALTER DATABASE [MovingBox] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MovingBox] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MovingBox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MovingBox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MovingBox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MovingBox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MovingBox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MovingBox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MovingBox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MovingBox] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MovingBox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MovingBox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MovingBox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MovingBox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MovingBox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MovingBox] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MovingBox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MovingBox] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MovingBox] SET  MULTI_USER 
GO

ALTER DATABASE [MovingBox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MovingBox] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MovingBox] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MovingBox] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MovingBox] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MovingBox] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MovingBox] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MovingBox] SET  READ_WRITE 
GO


